# Copyright (C) 2022-Present Indoc Systems
#
# Licensed under the GNU AFFERO GENERAL PUBLIC LICENSE,
# Version 3.0 (the "License") available at https://www.gnu.org/licenses/agpl-3.0.en.html.
# You may not use this file except in compliance with the License.
"""Add default casbin rules.

Revision ID: 0013
Revises: 0012
Create Date: 2026-02-19 15:04:31.299537
"""

from alembic import op
from sqlalchemy.orm.session import Session

from app.models.permissions import CasbinRule

revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = '0012'

DEFAULT_RULES = [
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': '*',
        'v2': 'announcement',
        'v3': 'create',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'collections',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'core',
        'v2': 'collections',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'copyrequest',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'greenroom',
        'v2': 'copyrequest_in_own_namefolder',
        'v3': 'create',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'file_any',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'file_any',
        'v3': 'upload',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'file_any',
        'v3': 'download',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'file_any',
        'v3': 'delete',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'file_any',
        'v3': 'copy',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'file_any',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'file_any',
        'v3': 'upload',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'file_any',
        'v3': 'download',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'file_any',
        'v3': 'delete',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'file_any',
        'v3': 'copy',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'file_in_own_namefolder',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'file_in_own_namefolder',
        'v3': 'upload',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'file_in_own_namefolder',
        'v3': 'download',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'file_in_own_namefolder',
        'v3': 'delete',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'file_in_own_namefolder',
        'v3': 'copy',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'upload',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'download',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'delete',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'copy',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'core',
        'v2': 'file_any',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'core',
        'v2': 'file_any',
        'v3': 'upload',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'core',
        'v2': 'file_any',
        'v3': 'download',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'core',
        'v2': 'file_any',
        'v3': 'delete',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'core',
        'v2': 'file_in_own_namefolder',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'core',
        'v2': 'file_in_own_namefolder',
        'v3': 'upload',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'core',
        'v2': 'file_in_own_namefolder',
        'v3': 'download',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'core',
        'v2': 'file_in_own_namefolder',
        'v3': 'delete',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'upload',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'download',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'delete',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'contributor',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'contributor',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'upload',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'contributor',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'download',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'contributor',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'delete',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': '*',
        'v2': 'invitation',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': '*',
        'v2': 'resource_request',
        'v3': 'create',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': '*',
        'v2': 'resource_request',
        'v3': 'create',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': '*',
        'v2': 'resource_request',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'tag',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'tag',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'core',
        'v2': 'tag',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'greenroom',
        'v2': 'tag',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'contributor',
        'v1': 'greenroom',
        'v2': 'tag',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': '*',
        'v2': 'users',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': '*',
        'v2': 'workbench',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': '*',
        'v2': 'workbench',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': '*',
        'v2': 'workbench',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'contributor',
        'v1': '*',
        'v2': 'workbench',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': '*',
        'v2': 'users',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'platform_admin',
        'v1': '*',
        'v2': 'notification',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': '*',
        'v2': 'project',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'contributor',
        'v1': '*',
        'v2': 'project',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': '*',
        'v2': 'project',
        'v3': 'view',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': '*',
        'v2': 'project',
        'v3': 'update',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'platform_admin',
        'v1': '*',
        'v2': 'project',
        'v3': 'create',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'platform_admin',
        'v1': '*',
        'v2': 'workbench',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': '*',
        'v2': 'file_attribute_template',
        'v3': 'manage',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'file_any',
        'v3': 'annotate',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'file_any',
        'v3': 'annotate',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'annotate',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'admin',
        'v1': 'core',
        'v2': 'file_in_own_namefolder',
        'v3': 'annotate',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'core',
        'v2': 'file_any',
        'v3': 'annotate',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'greenroom',
        'v2': 'file_in_own_namefolder',
        'v3': 'annotate',
        'v4': 'pilotdefault',
    },
    {
        'ptype': 'p',
        'v0': 'collaborator',
        'v1': 'core',
        'v2': 'file_in_own_namefolder',
        'v3': 'annotate',
        'v4': 'pilotdefault',
    },
]


def upgrade():
    session = Session(bind=op.get_bind())
    for rule in DEFAULT_RULES:
        exists = session.query(CasbinRule).filter_by(**rule).first()
        if not exists:
            session.add(CasbinRule(**rule))

    session.commit()


def downgrade():
    session = Session(bind=op.get_bind())
    for rule in DEFAULT_RULES:
        session.query(CasbinRule).filter_by(**rule).delete(synchronize_session=False)

    session.commit()
