# Copyright (C) 2022-Present Indoc Systems
#
# Licensed under the GNU AFFERO GENERAL PUBLIC LICENSE,
# Version 3.0 (the "License") available at https://www.gnu.org/licenses/agpl-3.0.en.html.
# You may not use this file except in compliance with the License.

"""Adding casbin table.

Revision ID: e86797550c26
Revises: 4f5ec3f0ac37
Create Date: 2022-03-25 14:36:06.799722
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e86797550c26'
down_revision = '4f5ec3f0ac37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'casbin_rule',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('ptype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('v0', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('v1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('v2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('v3', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('v4', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('v5', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='casbin_rule_pkey'),
        schema='pilot_casbin',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casbin_rule')
    # ### end Alembic commands ###
